### ISSUE TITLE
[BUG] - No padding for Laravel Nova Charts cards 

### ISSUE THREAD

**Issue by samrcruz** [coroo/nova-chartjs#140]
**Describe the bug**
there is no top padding on laravel nova 4

**To Reproduce**
add a simple larave nova chart example

**Expected behavior**
padding on the chartjs cards should be the same as normal laravel nova 4 cards

**Screenshots**
![image](https://user-images.githubusercontent.com/4487516/180765519-721b59a4-7880-4604-acae-ba07b85a2ffd.png)

**Dependencies Version (please complete the following information):**
 - Laravel Version: 9
 - Nova Version: 4 latest
 - Nova-ChartJS Version: 0.4.0

**Desktop (please complete the following information):**
 - MacOS Monterey
 - Browser Chrome
 - Version latest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Oskar-Mikael** [comment]
Issue still persists. The Card div's simply seem to be missing their padding classes

**Comment by coroo** [comment]
By default, the layout using this configuration:
`padding: {
              left: 20,
              right: 20,
              top: 0,
              bottom: 10
            }`

If you need to change the style padding, you can have it within this documentation: 
https://coroo.github.io/nova-chartjs/#/?id=layout

**Comment by CrystallDEV** [comment]
> By default, the layout using this configuration: `padding: { left: 20, right: 20, top: 0, bottom: 10 }`
> 
> If you need to change the style padding, you can have it within this documentation: https://coroo.github.io/nova-chartjs/#/?id=layout

This does not solve the underlying issue. As mentioned before: The card itself is missing the padding classes, which are also used by all the base nova metrics. Adding a padding to the chart itself does not fix the missing padding (for example for the title).

**Comment by benedict-w** [comment]
I also see the same issue, it's not the padding in the chart options, but the padding classes on the card that are missing.

Anyone know a workaround?

**Comment by fruitl00p** [comment]
We're seeing the same thing: the title is styled wrong (h4 vs h3 amoungst other things)
![image](https://github.com/coroo/nova-chartjs/assets/1492861/3cebca53-d20d-4303-a330-ce813f448b72)
