### ISSUE TITLE
Add date filter with date search

### ISSUE THREAD

**Issue by coroo** [coroo/nova-chartjs#21]
Need to add filter for user to have opportunity to see data with their own date search

**Comment by orangelabs-dev** [comment]
Any progress on this?

**Comment by coroo** [comment]
Still figuring out in this one. For filter any data using date for now only available with this feature : https://coroo.github.io/nova-chartjs/#/?id=adding-condition :pray:

**Comment by coroo** [comment]
Hi @orangelabs-dev , sorry for take so long for this feature. For now, we use button filter just like metrics-range in laravel nova. For using this feature, you need to use latest version (>v.0.2.1), also please see documentation in here: https://coroo.github.io/nova-chartjs/#/?id=metrics-filter
