### ISSUE TITLE
How to set options attribute of chartjs

### ISSUE THREAD

**Issue by phuclh** [coroo/nova-chartjs#23]
Thank you for this great package. I tried to hide the legend or call a callback function to format the label of yaxis. I did follow the instruction in Chartjs document, something like that:

```
(new BarChart())
    ->title('Expense')
    ->animations([
        'enabled' => true,
        'easing'  => 'easeinout',
    ])
    ->series(array([
        //'barPercentage'   => 1,
        'label'           => 'Average Sales 2',
        'backgroundColor' => '#F87900',
        'data'            => $chartData,
    ]))
    ->options([
        'xaxis'  => [
            'categories' => ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
        ],
        'legend' => [
            'display' => false
        ]
    ])
    ->width('2/3'),
```

But it didn't hide the legend. So does this great package follow the chartjs document or it has a different way to pass value to option attribute?

**Comment by mrpritchett** [comment]
I also would like to know this

**Comment by coroo** [comment]
Hi @phuclh & @mrpritchett, thank you for your feedback for this package. Unfortunately, we cannot set legend for now, but we will try to make sure you can configure the legend asap. Sorry for the inconvenience, will update this issue again soon.

**Comment by phuclh** [comment]
@coroo Thank you :D. If you can add a way to format number on the axis, that would be great too!!!!

**Comment by coroo** [comment]
Hi @phuclh & @mrpritchett , sorry for the inconvenience before. I already update the options behavior in nova-chartjs, so please use the latest update [v0.1.1](https://github.com/coroo/nova-chartjs/tree/v0.1.1) for this issue. Also, please see this documentation on how to hide legend: https://coroo.github.io/nova-chartjs/#/?id=legend

**Comment by phuclh** [comment]
Great support!!!

**Comment by bilogic** [comment]
@coroo I'm trying to use `beginAtZero` of chartjs, do you mean `->options(...)` is not passed into chartjs? Why not just pass it on as is, instead of having to write code for each option?
