### ISSUE TITLE
Feature Request: Clickable data

### ISSUE THREAD

**Issue by ekandreas** [coroo/nova-chartjs#28]
Possible action event when click inside a diagram/series to give the user custom data or redirect to another page.

**Comment by coroo** [comment]
Hi @ekandreas , thank you for your feedback for this package. Let we try to built event for that.

**Comment by coroo** [comment]
Hi @ekandreas , we already create feature for clickable chart or also using external link button.

- For using `external link` instead, please use this : [external-link](https://coroo.github.io/nova-chartjs/#/?id=external-link)
- For using `clickable chart`, please refer to this one : [clickable-point](https://coroo.github.io/nova-chartjs/#/?id=clickable-point)

Hopefully those help you :)
