### ISSUE TITLE
DoughnutChart white hole for items < 1%

### ISSUE THREAD

**Issue by 4n70w4** [coroo/nova-chartjs#29]
![image](https://user-images.githubusercontent.com/38257723/76305712-bbb5d200-62d6-11ea-9ae8-35243c6be600.png)

**Comment by coroo** [comment]
Hi @4n70w4 , sorry for the inconvenience. Let me check it first.

**Comment by coroo** [comment]
Hi @4n70w4 , I already check that one. 
Actually by default, there will be white border for doughnut and pie chart. For your case, we have some workaround. 
### Custom Data
If you using the custom data, you can use this code (add `border color` in series):
```php
(new DoughnutChart())
    ->title('Revenue')
    ->series(array([
        'data' => [100, 100, 100, 100, 100, 100, 100, 7],
        'backgroundColor' => ["#ffcc5c","#91e8e1","#ff6f69","#88d8b0","#b088d8","#d8b088", "#88b0d8", "#6f69ff"],
        'borderColor' => ["#ffcc5c","#91e8e1","#ff6f69","#88d8b0","#b088d8","#d8b088", "#88b0d8", "#6f69ff"],
    ]))
    ->options([
        'xaxis' => [
            'categories' => ['Portion 1','Portion 2','Portion 3','Portion 4','Portion 5','Portion 6','Portion 7','Portion 8']
        ],
    ])->width('1/3'),
```

### Laravel Model
But if you using `laravel model`, you can try this updated documentation for change the border color: https://coroo.github.io/nova-chartjs/#/?id=custom-border-color
*this required you to update to [v0.1.5](https://packagist.org/packages/coroowicaksono/chart-js-integration)

Hope this workaround help you
