### ISSUE TITLE
Support for Nova 1.*

### ISSUE THREAD

**Issue by JeanPrad0** [coroo/nova-chartjs#31]
Is there any technical reason why this package does not support the Nova 1.* version?

**Comment by coroo** [comment]
Hi @JeanPrad0 sorry for inconvenience. Unfortunately, I do test only using Nova 2.* version, so it recommend that we use Nova 2.*.

**Comment by JeanPrad0** [comment]
hi i'm using it with the Nova 1. *, i haven't had any problems yet. But I'm not using all the metrics

**Comment by coroo** [comment]
Hi @JeanPrad0 , if you dont mind, please let us know if any issue for nova 1.*. Hopefully if that still universal error (can be afford when using Nova 2.*), we will try to fix any issue in nova 1.*.

Meanwhile i will close this issue for now :)
