### ISSUE TITLE
Refresh button for custom chart.

### ISSUE THREAD

**Issue by phuclh** [coroo/nova-chartjs#33]
How can I use the refresh button for a custom chart? It seems like work with only Laravel Data Model chart.

I cache my chart data. It would be great if the refresh button can fire an event to delete cache or something else.

Thank you so much!

**Comment by coroo** [comment]
Hi @phuclh , for adding refresh button for a custom chart, you can add btnRefresh instead of the options.
```
(new StackedChart())
        ->title('Revenue')
        ->series(array([
            'barPercentage' => 0.5,
            'label' => 'Product #1',
            'backgroundColor' => '#ffcc5c',
            'data' => [30, 70, 80],
        ],[
            'barPercentage' => 0.5,
            'label' => 'Product #2',
            'backgroundColor' => '#ff6f69',
            'data' => [40, 62, 79],
        ]))
        ->options([
            'xaxis' => [
                'categories' => [ 'Jan', 'Feb', 'Mar' ]       
            ],
            'btnRefresh' => true
        ])
        ->width('1/3'),
```

For cache your data, can you explain to me more how you cache the chart data? Hope you can share your code to for easier understanding. Thank you

**Comment by phuclh** [comment]
Here is my code. I have a recursion function to get data from the database, so I cache it to optimize loading. The cache expires in 2 hours. The problem is sometimes I want to make my data fresh immediately. If I can listen the refresh button I can delete the cache.

```
$expiresAt = now()->addMinutes(120);

$report = Cache::remember('inventory_report_chart', $expiresAt, function () {
    $inventoryReportRegistry = resolve(InventoryReportRegistry::class);
    $products = Product::all();
    $options = ['type' => 'closing_stock'];

    return $inventoryReportRegistry->get('chart')->createReport($products, $options);
});

$chartData = [];
foreach ($report['chartData'] as $key => $item)
{
    $chartData[] = [
        'barPercentage' => 0.5,
        'label'         => $key,
        'borderColor'   => sprintf('#%06X', mt_rand(0, 0xFFFFFF)),
        'data'          => array_values($item),
    ];
};

return [
    (new LineChart())
        ->title('Inventory Report  ' . date('Y'))
        ->animations([
            'enabled' => true,
            'easing'  => 'easeinout',
        ])
        ->series($chartData)
        ->options([
            'xaxis' => [
                'categories' => $report['months']
            ],
            //'btnRefresh' => true
        ])
        ->width('full'),
];
```

**Comment by coroo** [comment]
Hi @phuclh , thank you for share your code. Actually, Im just thinking if we add `Cache::forget('key');` , it would be delete your cache, right? 
but how your data will be provided then since it only delete your last cache, but not reproduce the new one?

In other hand, i'm thinking another workaround. how if we create an option for btnRefresh to has function to refresh page instead of one card only?

**Comment by coroo** [comment]
Hi @phuclh , regarding this issue and my statement before. We already release new version for your workaround. So, instead of using `refresh`, you can use `reload`. 

Please see detail documentation here:
https://coroo.github.io/nova-chartjs/#/?id=reload

Hope this one help this issue.

**Comment by phuclh** [comment]
> Hi @phuclh , regarding this issue and my statement before. We already release new version for your workaround. So, instead of using `refresh`, you can use `reload`.
> 
> Please see detail documentation here:
> https://coroo.github.io/nova-chartjs/#/?id=reload
> 
> Hope this one help this issue.

Thank you for the new release, but I think the reload button doesn't solve my problem because the cache is still there even you click refresh or reload button.

```
$expiresAt = now()->addMinutes(120);

$report = Cache::remember('inventory_report_chart', $expiresAt, function () {
    $inventoryReportRegistry = resolve(InventoryReportRegistry::class);
    $products = Product::all();
    $options = ['type' => 'closing_stock'];

    return $inventoryReportRegistry->get('chart')->createReport($products, $options);
});
```

My code retrieves all reports from the cache or, if they don't exist, retrieve them from the database and add them to the cache. So if the reload can run the `Cache::forget('inventory_report_chart')'`, it would be great.

**Comment by coroo** [comment]
Hi again @phuclh ,

regarding your code, since for now we not used any cache related code, how if you remove cache at the first of your code. so it would be like:
```
Cache::forget('inventory_report_chart'); //make the cache expired first
$expiresAt = now()->addMinutes(120);

$report = Cache::remember('inventory_report_chart', $expiresAt, function () {
    $inventoryReportRegistry = resolve(InventoryReportRegistry::class);
    $products = Product::all();
    $options = ['type' => 'closing_stock'];

    return $inventoryReportRegistry->get('chart')->createReport($products, $options);
});```

Sorry but we will try to figure it out again, does it perfect to use cache rather than direct connection to database for get any data. Also, please let me know if the code above can help you. thank you

**Comment by phuclh** [comment]
> Hi again @phuclh ,
> 
> regarding your code, since for now we not used any cache related code, how if you remove cache at the first of your code. so it would be like:
> 
> ```
> Cache::forget('inventory_report_chart'); //make the cache expired first
> $expiresAt = now()->addMinutes(120);
> 
> $report = Cache::remember('inventory_report_chart', $expiresAt, function () {
>     $inventoryReportRegistry = resolve(InventoryReportRegistry::class);
>     $products = Product::all();
>     $options = ['type' => 'closing_stock'];
> 
>     return $inventoryReportRegistry->get('chart')->createReport($products, $options);
> });
> ```
> 
> Sorry but we will try to figure it out again, does it perfect to use cache rather than direct connection to database for get any data. Also, please let me know if the code above can help you. thank you

That code doesn't help because every time I visit my resource page it will delete the old cache and create the new one, it doesn't seem to make sense. My expect is delete the cache when the reload/refresh button was clicked (when I visit or F5 the page, it still uses the data from cache).
