### ISSUE TITLE
Clicking on metrics to refresh/reload charts

### ISSUE THREAD

**Issue by shenjiayu** [coroo/nova-chartjs#35]
First of all, thanks for putting your time developing this amazing integration.

My use case is having more than one metrics which could be total visitors, new visitors, etc as the first panel and clicking on any of them would drill down a collection of charts below as the second panel, and all charts in the second panel should be refreshed/reloaded accordingly while clicking around the metric in the first panel.

I don't know if it is feasible in Nova. Maybe it's not the correct place to ask this question. Kindly close it, if it's not related.

**Comment by coroo** [comment]
Hi @shenjiayu , 

Thank you for your interest with this component.
But can you please explain a little bit more, what is your meaning of panel?
It will be better if you can share any images :)

**Comment by shenjiayu** [comment]
@coroo 
Hmm..I found the workaround to fix this issue..Rather than finding a way to override the dashboard, I can create a tool page where I have full control of the page myself.
