### ISSUE TITLE
charts not showing

### ISSUE THREAD

**Issue by chorton** [coroo/nova-chartjs#37]
I'm running Laravel Nova v2.12.0 and nova-chartjs v0.2.3

I'm following the instructions in the getting started section at https://coroo.github.io/nova-chartjs/#/?id=getting-started

When I add the StackedChart example and load the dashboard, I do not see any chart display, and when I look at the source, I see the following:

`<stacked-chart card="[object Object]" lens="" class="card-panel"></stacked-chart>`

cart="[object Object]" doesn't seem right.  Is it?

Regardless, I cannot get charts to show at all.

**Comment by coroo** [comment]
Hi @chorton ,

I already test in my local again using nova-chartjs v0.2.3 without any errors.
Have you try to use incognito mode? Just want to make sure there is no cache problem.

Also, please make sure your code should be like this:
File: app/Providers/NovaServiceProvider.php
```
     /**
     * Get the cards that should be displayed on the default Nova dashboard.
     *
     * @return array
     */
    protected function cards()
    {
        return [
            (new StackedChart())
                ->title('Revenue')
                ->series(array([
                    'barPercentage' => 0.5,
                    'label' => 'Product #1',
                    'backgroundColor' => '#ffcc5c',
                    'data' => [30, 70, 80],
                ],[
                    'barPercentage' => 0.5,
                    'label' => 'Product #2',
                    'backgroundColor' => '#ff6f69',
                    'data' => [40, 62, 79],
                ]))
                ->options([
                    'xaxis' => [
                        'categories' => [ 'Jan', 'Feb', 'Mar' ]       
                    ],
                ])
                ->width('1/3'),
        ];
    }
```

<img width="771" alt="Screen Shot 2020-04-08 at 19 07 03" src="https://user-images.githubusercontent.com/13533557/78782797-c6927e00-79cc-11ea-9a70-03634d11050f.png">
