### ISSUE TITLE
Please don't add fontawesome inline

### ISSUE THREAD

**Issue by ekandreas** [coroo/nova-chartjs#38]
Please, remove the fontawesome inside the component that destroys any other use of fontawesome pro.
`https://use.fontawesome.com/releases/v5.2.0/css/all.css` should not be placed inline in any case...

**Comment by coroo** [comment]
Hi @ekandreas , sorry for the inconvenience, for that font awesome, we will remove in next release.
again thank you for your feedback.

**Comment by coroo** [comment]
This issue has been solved in [v0.2.4](https://github.com/coroo/nova-chartjs/blob/master/CHANGELOG.md).

**Comment by vesper8** [comment]
@coroo I think that as a result of removing font awesome, the refresh button, and possibly other buttons, now show a blank icon unless you manually add font awesome. Yet it seems that the installation documentation does not mention that you must manually add font awesome
