### ISSUE TITLE
Areachart does not support RGBA color values

### ISSUE THREAD

**Issue by michaelw85** [coroo/nova-chartjs#46]
Areachart uses a brighten function that only supports hex values while chartjs supports RGBA.
See code [here](https://github.com/coroo/nova-chartjs/blob/master/src/AreaChart.php#L37).

**Comment by coroo** [comment]
Hi @michaelw85 , if you dont mind. Could you help us to do testing for using RGBA in this version:
```
composer require coroowicaksono/chart-js-integration:dev-issues-46
```

**Comment by michaelw85** [comment]
> Hi @michaelw85 , if you dont mind. Could you help us to do testing for using RGBA in this version:
> 
> ```
> composer require coroowicaksono/chart-js-integration:dev-issues-46
> ```

Sorry for the late reply, I'm a bit short on time right now but I will try to test it asap.

**Comment by coroo** [comment]
Release in [v0.2.5](https://github.com/coroo/nova-chartjs/tree/v0.2.5).

*If anyone has a same problem with this one, please re-create different ticket.
