### ISSUE TITLE
Error work Postgres

### ISSUE THREAD

**Issue by hakerkiler** [coroo/nova-chartjs#52]
I have error
SQLSTATE[42703]: Undefined column: 7 ERROR:  column "%b %Y" does not exist LINE 1: select DATE_FORMAT(transactions.created_at, "%b %Y") AS cat

Laravel
Database - Postgres

**Comment by coroo** [comment]
Hi @hakerkiler , thank you for your interest in this package.
Unfortunately I'm not yet do testing using postgresql before. Let me try to check it first and update this one soon.

**Comment by coroo** [comment]
Hi @hakerkiler , I already test using postgresql and there is no error.
Have you check your `transaction` table contain of `created_at` column ?

https://coroo.github.io/nova-chartjs/#/?id=use-laravel-model

**Comment by hakerkiler** [comment]
Hi @coroo yes I have created_at column in table

My table sql

create table transactions
(
    id              bigserial                  not null
        constraint idx_38174_primary
            primary key,
    user_id         bigint,
    type            varchar(255),
    sum             numeric,
    percent         numeric,
    sum_from        numeric,
    sum_to          numeric,
    requisite       varchar(255),
    status          bigint,
    additional_data text,
    created_at      timestamp(0),
    updated_at      timestamp(0),
    deleted_at      timestamp(0),
    currency_id     bigint default '1'::bigint not null,
    ref_point       bigint
);


In Postgres I found some error in file "TotalRecordsController.php"

`foreach($request->series as $seriesKey => $serieslist){
                    $seriesData = json_decode($serieslist);
                    $filter = $seriesData->filter;
                    $labelList[$seriesKey] = $seriesData->label;
                    if(empty($filter->value)){
                        $seriesSql .= ", SUM(CASE WHEN ";
                        $countFilter = count($filter);
                        foreach($filter as $keyFilter => $listFilter){
                            $seriesSql .= " ".$listFilter->key." ".($listFilter->operator ?? "=")." '".$listFilter->value."' ";
                            $seriesSql .= $countFilter-1 != $keyFilter ? " AND " : "";
                        }
                        $seriesSql .= "then ".$calculation." else 0 end) as '".$labelList[$seriesKey]."'";
                    } else {
                        $seriesSql .= ", SUM(CASE WHEN ".$filter->key." ".($filter->operator ?? "=")." '".$filter->value."' then ".$calculation." else 0 end) as '".$labelList[$seriesKey]."'";
                    }
                }`

this code is work wrong because 

'".$labelList[$seriesKey]."' this moment in postgress work like theat  ".$labelList[$seriesKey]."
and 
'".$labelList[$seriesKey]."' this too

< ' > error given

**Comment by coroo** [comment]
Hi @hakerkiler it would be nice if you can share the error screenshot since I can’t reproduce any error using postgres.

**Comment by hakerkiler** [comment]
<img width="1289" alt="Снимок экрана 2020-06-20 в 19 12 46" src="https://user-images.githubusercontent.com/10829306/85206338-090bfb80-b32a-11ea-8854-17a2e5a28259.png">


this code work for me in Postgress 12

**Comment by hakerkiler** [comment]
<img width="1289" alt="Снимок экрана 2020-06-20 в 19 14 10" src="https://user-images.githubusercontent.com/10829306/85206356-39ec3080-b32a-11ea-9b39-9e9d4958dfa0.png">

And DATE_FORMAT(transactions.created_at, "%b %Y")
its change to to_char

**Comment by 949mac** [comment]
I'm using Postgres 11 and have the same error:

![image](https://user-images.githubusercontent.com/23151962/87209589-47f8f580-c2c7-11ea-904c-6206e20a55c6.png)

**Comment by hakerkiler** [comment]
> I'm using Postgres 11 and have the same error:
> 
> ![image](https://user-images.githubusercontent.com/23151962/87209589-47f8f580-c2c7-11ea-904c-6206e20a55c6.png)

$query = $model::selectRaw('to_char('.$xAxisColumn.', \'%b %Y\') AS cat, to_char('.$xAxisColumn.', \'%Y-%m\') AS catorder, sum('.$calculation.') counted'.$seriesSql);

change to this

**Comment by coroo** [comment]
Fix in [v0.3.1](https://github.com/coroo/nova-chartjs/blob/master/CHANGELOG.md#v031---2020-09-15)
