### ISSUE TITLE
How can I make modifications to bar-chart.js

### ISSUE THREAD

**Issue by xoco70** [coroo/nova-chartjs#55]
Hi, 

I'm trying to change bar-chart.js for debug purpose. 

I change it, but I cannot see any changes in my graph.

I went `chart-js-integration` vendor folder, and ran:

```
npm install
npm run watch
```

Both command worked well.

But nothing happens. Am I doing thing right ?

My purpose is to get the scope of what I can do with your plugin, and what I cannot do.

I am not so used to code with VueJS, so, it is a bit difficult.

**Comment by xoco70** [comment]
I could do it, just need a refresh without cache in chrome

**Comment by xoco70** [comment]
I tried to add extra text in BarChart.vue,  for instance:

      <h4 class="chart-js-dashboard-title">{{ checkTitle }} extraText blabla</h4>

but it isn't rendered when I do 

`npm run watch`

in `/vendor/coroowicaksono/chart-js-integration`

I can see laravel mix working: 

```
 DONE  Compiled successfully in 177ms                                                                                                                                                                                9:44:48 AM

                      Asset      Size                    Chunks             Chunk Names
/js/chart-js-integration.js  1.37 MiB  /js/chart-js-integration  [emitted]  /js/chart-js-integration

```

and inside `chart-js-integration.js` is the reference for BarChart.vue

Is it the way I am supposed to do it ?

**Comment by coroo** [comment]
Hi @xoco70 .

Instead of add extra text by yourself, can you explore to us more what your point to add extratext instead of using [title](https://coroo.github.io/nova-chartjs/#/?id=basic-usage) ? And yes, I think what you've done already correct you need to `npm install` and run by `npm run watch` or `npm run prod`
