### ISSUE TITLE
LineChart defaulting to BarChart visually

### ISSUE THREAD

**Issue by TimRoenicke** [coroo/nova-chartjs#67]
Nova:  v3.8.4
Laravel:  7.27.0

```php
(new LineChart())
            ->title('Number of Orders By Week')
            ->model('\App\Order')
            ->options(
                [
                    'uom' => 'week', // available in 'day', 'week', 'month', 'hour'
                    'startWeek' => '1',
                    'latestData' => 30
                ])->width('1/2'),
```

Is displaying a bar chart by default unless I segment with `->series(...)`.  Is there a way to display a single line chart when using `->model(...)`? I have a feeling I'm overlooking something quite obvious. 😅

**Comment by coroo** [comment]
Hi @TimRoenicke , 

Thank you for reporting bug. Please use v0.3.2 or the latest version for fix this issue.
Detail update in [here](https://github.com/coroo/nova-chartjs/blob/master/CHANGELOG.md#v032---2020-09-17)
