### ISSUE TITLE
[BUG] Chart renders out of card

### ISSUE THREAD

**Issue by Hieu401** [coroo/nova-chartjs#74]
Hello,

Sorry if I am violating any rules or made any obvious mistakes, I'm an intern and this is my first bug report, so please bear with me.

Whenever I try to display any charts from the package in Nova, the charts are rendered outside of the cards. The problem ensues even with the hardcoded example code from the documentation. I haven't changed anything from the code. I thought that it might be me, but apparently the other developers have had similar experiences where the interface is not working properly.

![chartJSIssue](https://user-images.githubusercontent.com/44575927/101916808-bbc96200-3bc7-11eb-8544-234cee82630d.png)

We are working with
 - Laravel version 8.18.1
 - Nova version 3.16.3
 - Nova-ChartJS version 0.3.2

I'm opening my Nova CMS on
 - OS: Windows 10
 - Browser firefox 83.0

Do note that I'm on a virtual machine and I am using Homestead, though I don't think this should be a problem since my coworkers are not using Homestead and are experiencing the same issue.

I hope I've provided the appropriate information so people can help me. I love how the charts look and the many options it procides. Hopefully this issue is solvable so the package can be integrated within the project.

**Comment by ekandreas** [comment]
Why do the component put p-10 on the same node as the card?
It should be possible to override.

**Comment by Hieu401** [comment]
> 
> 
> Why do the component put p-10 on the same node as the card?
> It should be possible to override.

Thanks for your help
I'm not sure why it does that or what you mean.
Do you mean to override in a custom CSS file?

**Comment by iamoat** [comment]
Need to rebuild StackedChart.vue and etc. 

Replace <card class="p-10"> with <card class="">

Then do

npm install

npm run prod

if you get an error about compiling @babel/compat-data, then do the following

npm update --depth 5 @babel/compat-data

**Comment by Hieu401** [comment]
> 
> 
> Need to rebuild StackedChart.vue and etc.
> 
> Replace
> 
> `<card class="p-10">`
> with
> `<card class="">`
> 
> Then do
> 
> npm install
> 
> npm run prod
> 
> if you get an error about compiling @babel/compat-data, then do the following
> 
> npm update --depth 5 @babel/compat-data

Sorry for the wait. I've followed your instructions, but unfortunately the problem persists.

**Comment by ndberg** [comment]
I had the same problem, it came from this package, which I had installed: https://github.com/austinkregel/nova-failed-jobs-tool

It adds style to the p-10 class.

When I removed it, it was okay.

**Comment by Hieu401** [comment]
> I had the same problem, it came from this package, which I had installed: https://github.com/austinkregel/nova-failed-jobs-tool
> 
> It adds style to the p-10 class.
> 
> When I removed it, it was okay.

Thanks for the suggestion. We don't use that package, but perhaps it might be another package that interferes with the styling.

**Comment by Pondake** [comment]
This is a very impressive package. Styling usually shouldn't take this long to fix. Is this still relevant?

**Comment by Hieu401** [comment]
This issue is no longer relevant for us since we have moved on from Laravel Nova. Thanks everyone for the help, but unfortunately I am unable to provide a solution to the issue. I am closing this thread.

**Comment by Tim-Frensch** [comment]
This issue only appears for me when i use a nova package which installs the missing tailwind css classes.
