### ISSUE TITLE
[BUG] Error when series filter value is empty

### ISSUE THREAD

**Issue by brandonkhj** [coroo/nova-chartjs#76]
Hits count() error when series > filter > value is empty.

Example of written code -
`                ->series(array([
                    'label' => 'Test',
                    'filter' => [
                        'key' => 'column',
                        'operator' => 'IS NULL'
                    ],
                ],
`

Error got in DevTools network -
`
exception: "ErrorException" 
file: "D:\path\vendor\coroowicaksono\chart-js-integration\src\api\TotalRecordsController.php" 
line: 56
message: "count(): Parameter must be an array or an object that implements Countable"
`

Working with - 
 - Laravel Version: v5.8
 - Nova Version: v2
 - Nova-ChartJS Version: v0.3.2

 - OS: Window 10
 - Browser: Chrome
 - Version: 87

**Comment by shawngoh87** [comment]
@coroo any comments on this issue? there is a PR ready on this (#79)

**Comment by coroo** [comment]
Sorry for too late response since I'm not focus in this one again.
