### ISSUE TITLE
[BUG] Multiple instances of the same chart throw duplicate key error

### ISSUE THREAD

**Issue by stomaskov** [coroo/nova-chartjs#82]
**Describe the bug**
If there are multiple instances of the same chart, r.g. bar-chart on the same page they have the same UriKey and it throws error in the console: "[Vue warn]: Duplicate keys detected: 'bar-chart.undefined'. This may cause an update error."

**To Reproduce**
Create multiple charts of the same type on one page. Check console.

**Expected behavior**
Different uriKey for every instance and no errors.

**Dependencies Version (please complete the following information):**
 - Laravel Version: 7.30.4
 - Nova Version: 3.21
 - Nova-ChartJS Version: v0.3.2

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Firefox
 - Version 84

**Comment by SadeghPM** [comment]
Quick fix:
Create new chart class and extened main chart:
```php
<?php
namespace App\Nova\Metrics;

class BarChart extends \Coroowicaksono\ChartJsIntegration\BarChart
{
    public function uriKey(string $uriKey)
    {
        return $this->withMeta(['uriKey' => $uriKey]);
    }
}
```

use this class for char and set key with new function `uriKey`:
```php
...
App\Nova\Metrics\BarChart::make()->uriKey('unique-key')->label('...');
```
