### ISSUE TITLE
Polar Chart

### ISSUE THREAD

**Issue by coroo** [coroo/nova-chartjs#9]
As Chart JS Integration’s user,
I need to have polar chart
So that I can have polar chart view

**Comment by FabioSTI** [comment]
I second this request. It would be really nice to have it.

**Comment by coroo** [comment]
Hi @FabioSTI , thank you for your feedback for this feature. We already release new version to have this polar area chart, so please dont forget to update to latest version (>=0.2.3) of this package.

For detail documentation, please find : 
https://coroo.github.io/nova-chartjs/#/?id=polar-area-chart
